version: "3"

services:
  inertia_generator:
    container_name: inertia_generator
    image: inertia_generator
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - generator-network
    # depends_on:
    #     - redis
    #     - mysql
    #     - mongodb

  # supervisor:
  #   container_name: supervisor
  #   image: supervisor
  #   build: supervisord/.
  #   volumes:
  #     - .:/var/www/html
  #   networks:
  #     - generator-network
  #   depends_on:
  #     - mailer

  inertia_generator_redis:
    container_name: inertia_generator_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - generator-network

  pgsql:
    image: postgres:14.5-alpine3.16
    restart: "no"
    container_name: generator-pgsql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=generatorpgsql
      - POSTGRES_DB=generator
    volumes:
      - generator-pgsql:/var/lib/postgresql/data
    networks:
      - generator-network
    ports:
      - 5432:5432

networks:
  generator-network:
    external: true

volumes:
  generator-pgsql:
